### ISSUE TITLE
support for youtube-nocookie domain

### ISSUE THREAD

**Issue by SilkeDX** [nitsan-technologies/ns_youtube#1]
Hi,
would it be possible to add the possibility to add the youtube videos with the nocookie domain of youtube?
Thanks a lot!

**Comment by nitsan-technologies** [comment]
we have already implemented you can find it in a single video 


![image](https://github.com/nitsan-technologies/ns_youtube/assets/2622317/3abb00ba-d6d4-4aca-b40a-0c9dd275c581)
