### ISSUE TITLE
Requests from referer <empty> are blocked.

### ISSUE THREAD

**Issue by danielpesel** [nitsan-technologies/ns_youtube#2]
Hi, i try to get the plugin to work but have a problem.

i am using Typo3 10 install through composer and get this error "Requests from referer <empty> are blocked."
i did everything as written in the documentary.
in the browser console i see these error 
Uncaught TypeError: initSrc is undefined
    <anonymous> https://t3.pluspunktleben.de/typo3conf/ext/ns_youtube/Resources/Public/Js/script.js?1586772214:16
    jQuery 2
        each
        each
    <anonymous> https://t3.pluspunktleben.de/typo3conf/ext/ns_youtube/Resources/Public/Js/script.js?1586772214:4
    jQuery 13
        e
        t
        setTimeout handler*l/<
        c
        fireWith
        fire
        c
        fireWith
        ready
        B
        EventListener.handleEvent*
        <anonymous>
        <anonymous>

can you help me?

Thanks!!

**Comment by nitsan-technologies** [comment]
Thank you for reporting the issue 

The problem has been resolved and you can expect to see the solution implemented in the next release.
