### ISSUE TITLE
TYPO3 12.4 Compatible Version

### ISSUE THREAD

**Issue by devtroll** [nitsan-technologies/ns_youtube#7]
Is there any information yet when this extension will be available for TYPO3 v12?

Greetings

**Comment by nitsan-technologies** [comment]
Hey @devtroll 

Our team is working on the v12 compatibility of all our TYPO3 extensions. We should release it within ~2 weeks. Keep subscribing to new releases to get notifications ;) Thanks for your patience and support.

Cheers, Team NITSAN

**Comment by devtroll** [comment]
Thank you for the information. I am looking forward to the release!
